language: node_js
sudo: required
dist: trusty
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "node"
install:
  - npm install
  - npm install -g polymer-cli
  - polymer install
  - polymer build
script:
  - cp .surgeignore ./build/default
  - surge build/default https://rmit-promos.surge.sh --token $SURGE_TOKEN
